### ISSUE TITLE
cuda out of memory when test

### ISSUE THREAD

**Issue by mooncakehub** [drprojects/superpoint_transformer#21]
Hi Damien,
  When I tested, my cuda of memory ran out.However,I can train s3dis =11g.I want to know how much cuda memory is needed for test.

Beside, I have trained s3dis-11g for 500 epochs,wanb shows me state of crashed.

![1692257616580](https://github.com/drprojects/superpoint_transformer/assets/138660085/098e28e0-b509-4ff6-9803-fd9af55a15af)

**Comment by mooncakehub** [comment]
![1692257723374](https://github.com/drprojects/superpoint_transformer/assets/138660085/df6a2a18-4166-44cb-9c01-97a205689dd0)

I don't know if this represents completion or a bug

**Comment by drprojects** [comment]
Hi, 

All default configs should work on a 32G device, both for training and evaluation.

- What is your GPU device ? 
- How much memory does your GPU have ? 
- Did you make sure you **stopped all other GPU processes before running the code** ? _eg_ if you are running on your local workstation your GUI, or your browser  could be consuming GPU mmeory too. To this end, use `nvidia-smi` to make sure no other process is running on your device.

Regarding the crashing of your `s3dis-11g` training, I cannot interepret results from your screenshot. Please share the full traceback log. You may find it under the **`Logs`** section of your wandb experiment's dashboard:

![image](https://github.com/drprojects/superpoint_transformer/assets/42056973/b379a2f0-881d-40a8-a4e6-37bf9306be2a)

**Comment by mooncakehub** [comment]
my device is nvidia-2080, it has 12G memory。so I can only run the s3dis-11g.I also want to know that whether the results of the test will be printed on the screen。when I finished running s3dis-11g,it would show me test ruslut on the screen,like this:
![微信图片_20230822153724](https://github.com/drprojects/superpoint_transformer/assets/138660085/064ba319-9756-453a-8eec-ae80173b156c)

**Comment by drprojects** [comment]
> thanks for your reply，this is my logs ![3dc4925cba369a072ede893c3c44036](https://user-images.githubusercontent.com/138660085/262269398-b52b78f0-72a7-4929-a3a0-4c64c33a3ced.png)

I do not see any error message and it seems the training reached 500 epochs as expected. Is this the 'crashed' run you were mentionning ? If so, when did it crash ? What are the logs on your device's CLI ? 



> my device is nvidia-2080, it has 12G memory。so I can only run the s3dis-11g.I also want to know that whether the results of the test will be printed on the screen。when I finished running s3dis-11g,it would show me test ruslut on the screen,like this: ![微信图片_20230822153724](https://user-images.githubusercontent.com/138660085/262271746-064ba319-9756-453a-8eec-ae80173b156c.jpg)

Do you have an **RTX 2080** or an **RTX 2080 Ti** ? The latter has **11G memory** but the former only has **8G memory**...

To be honest, I do not understand this issue, your messages seem to indicate you can run the training of `s3dis-11g` without problem and the above screeenshot shows the final computation of test scores works too. So, what is the problem ?

**Comment by mooncakehub** [comment]
thank you for your reply,you really help me a lot.and I have a  RTX 2080 Ti ,I am sorry.
beside,I want to know where can I modify the gpu code,such as chagging the default 0 to 2

**Comment by drprojects** [comment]
This is usually done by setting your `CUDA_VISIBLE_DEVICES` environment variable, _ie_:

```bash 
CUDA_VISIBLE_DEVICES=2
```

**Comment by drprojects** [comment]
I consider this issue solved, closing it.
